WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7421b1d9dc40>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/ruff/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7421b0f23920>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/ruff/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7421b0dcac60>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/ruff/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7421b0dcae70>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/ruff/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7421b0dcb080>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/ruff/
ERROR: Could not find a version that satisfies the requirement ruff (from versions: none)
ERROR: No matching distribution found for ruff
